### ISSUE TITLE
Clang static analyser

### ISSUE THREAD

**Issue by andrewleech** [resea/history#1]
Hi,
I'm really interested in you codeclimate-clang-static-analyzer docker which has been taken down :-(

Is there any chance you could share it again?

**Comment by seiyanuta** [comment]
Hi @andrewleech!

I never thought that somebody use my repositories. I have restored the codeclimate-clang-static-analyzer at:

https://github.com/seiyanuta/codeclimate-clang-static-analyzer

This repository includes changes from original one to follow latest codeclimate spec. It should work fine. I will never remove my repositories again :D

**Comment by andrewleech** [comment]
That's great, thanks a lot!
